from .product import Product
from .beverage.beverage import Beverage
from .beverage.coffee import Coffee
from .beverage.cold_beverage import ColdBeverage
from .beverage.hot_beverage import HotBeverage
from .beverage.tea import Tea
from .food.cake import Cake
from .food.dessert import Dessert
from .food.food import Food
from .food.main_dish import MainDish
from .food.salmon import Salmon
from .food.soup import Soup
from .food.starter import Starter