from ..product import Product
from ..beverage.beverage import Beverage
from ..beverage.coffee import Coffee
from ..beverage.cold_beverage import ColdBeverage
from ..beverage.hot_beverage import HotBeverage
from ..beverage.tea import Tea
from .cake import Cake
from .dessert import Dessert
from .food import Food
from .main_dish import MainDish
from .salmon import Salmon
from .soup import Soup
from .starter import Starter